config/routes.rb
NineGag::Application.routes.draw do

  get "users/destroy"

  resources :images do
    match '/like',    to: 'images#upvote'
    match '/dislike', to: 'images#downvote'

    resources :microposts
  end

  devise_for :users
  resources :users

  root :to => 'home#index'
  match '/help',    to: 'home#help'
  match '/about',   to: 'home#about'
  match '/images',  to: 'images#destroy', via: :delete
  match '/profile', to: 'home#profile'
  match '/users',   to: 'users#index'

end

app/models/image.rb
class Image < ActiveRecord::Base
  # attr_accessible :title, :body
  attr_accessible :picture, :likes, :unlikes, :user_id
  has_attached_file :picture, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates :user_id, presence: true
  serialize :likes
  serialize :unlikes
  belongs_to :user
  has_many :microposts, dependent: :destroy
  default_scope :order => "created_at DESC"

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  attr_accessible :content, :image_id, :user_id
  belongs_to :user
  belongs_to :image
  validates :content, presence: true, length: { maximum: 140 }
  validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :email, :name
  validates :email, presence: true
  has_many :images
  has_many :microposts, dependent: :destroy
  #validates :email, uniqueness: {case_sensitive: false}

  before_create :set_name

  def set_name
   
    self.name = email.split("@").first.split(".").first
  end

  def admin?
     email == "marko.siftar@gmail.com"
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @image = Image.new
    @images = Image.page(params[:page] || 0).per(5)
    @users = User.all
    
    @micropost = Micropost.new
    @microposts = Micropost.all
  end

  def help
  
  end

  def about
  
  end

  def profile
    
  end
  
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def create
    @image = Image.create(params[:image])

    @image.update_attributes(:user_id => current_user.id)
    redirect_to root_path, notice: "Upload successfully."
  end

  def show
    image = Image.find(params[:id])

    render :inline => "<%= image_tag image.picture.url %>",:locals => {:image => image}
  end
  def destroy
    image = Image.find(params[:id])
    image.destroy
    flash[:notice] = "Picture destroyed."
    redirect_to root_url
  end

def upvote

  image = Image.find(params[:image_id])

  likes = image.likes || []
  image.update_attributes(:likes => likes << current_user.id) unless (likes.include?(current_user.id) ||
      image.unlikes.to_a.include?(current_user.id))

  redirect_to root_path, notice: "You like photo!"
end

def downvote

  image = Image.find(params[:image_id])

  unlikes = image.unlikes || []
  image.update_attributes(:unlikes => unlikes << current_user.id) unless (unlikes.include?(current_user.id) ||
      image.likes.to_a.include?(current_user.id))

  redirect_to root_path, notice: "You don't like photo!"
end


end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_filter :authenticate_user!, only: [:create, :destroy]

  def index

  end

  def create
    image = Image.find(params[:image_id])
    @micropost = image.microposts.build(params[:micropost]
                                        .merge(:user_id => current_user.id))

    if @micropost.save
      flash[:notice] = "Comment created!"
      redirect_to root_url
    else
      flash[:alert] = "Comment can't be blank"
      redirect_to root_url
    end
  end

  def destroy
    image = Image.find(params[:image_id])
    micropost = image.microposts.find(params[:id])
    micropost.destroy
    flash[:notice] = "Comment destroyed."
    redirect_to root_url
  end
  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
  def show
   @user = User.find(params[:id])
  end
  def destroy
    user = User.find(params[:id])
    if user.destroy
      flash[:notice] = "User destroyed successfully"
      redirect_to root_path
    else
      flash[:alert] = "Didn't destroy user!!!"
    end
  end

end
    

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/about.html.erb
<%  provide(:title, 'About') %>
<h1>About</h1>
<p>
  This is the simple RoR copy of 9gag
</p>

app/views/home/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  This is the help page.
</p>

app/views/home/home.html.erb
<div id="whole_page">
<% if current_user %>
  
  <p>
  Would you like to upload a new image?
  </p>

  <%= form_for @image, :url => images_path, :html => { :multipart => true } do |form| %>
    <%= form.file_field :picture %>
    <%= form.submit "Upload" %>
  <% end %>


  <% end %>



<hr/>
<%= render :partial => "images/all" %>
<hr/>

</div>

app/views/home/index.html.erb
<div id="whole_page">
<% if current_user %>
  <br/>
  <% if current_user.images.count == 0 %>
    You don't have any uploaded images!
  <% elsif current_user.images.count == 1 %>
    You have 1 uploaded image!
  <% else %>
  You have <%= current_user.images.count %> uploaded images!
  <% end %>
  <p>
  Would you like to upload a new one?
  </p>

  <%= form_for @image, :url => images_path, :html => { :multipart => true } do |form| %>
    <%= form.file_field :picture %>
    <%= form.submit "Upload" %>
  <% end %>


  <% end %>



<hr/>

<%= render :partial => "images/all" %>

<%= paginate @images %>

</div>

app/views/home/profile.html.erb
<%  if current_user %>
<h1>Your PROFILE</h1>
Comments (<%= current_user.microposts.count %>)
<br/>
Uploaded images (<%= current_user.images.count %>)
<hr/>
<br/>
<%if current_user.admin?%>
Admin
<%else%>
User
<%end%>
<br/><br/>
<hr/>
Name: <%= current_user.name.capitalize %>
<br/>
Email: <%= current_user.email %>
<br/>


<h1><%=  gravatar_for(current_user) %></h1>
<br/>
<%= link_to "Delete your profile", user_path(current_user.id), :method => :delete %>
<% end %>

app/views/images/_all.html.erb
<% @images.each do |image| %>
<% if current_user %>
<b class="mini_view">Uploaded by:
<% @users.each do |user| %>
  <% if user.id == image.user_id %>
    <%= link_to user.name.capitalize, user_path(image.user_id)%></b>
  <% end %>
<% end %>

<br/>
<% end %>
<%= link_to(image_tag(image.picture.url(:medium)),image) %>

<% if current_user && current_user.admin?%>
  <%= form_for image, :url => image, :html => { :method => :delete } do |f|%>
    <div class="button">
      <%= f.submit "Delete" %>
    </div>
  <% end %>
<% end %>

<% if current_user %>
  
    <%= form_for image, :url => image_like_path(image) do |f|%>
      <div class="text">
        <% if !image.likes.to_a.include?(current_user.id) && !image.unlikes.to_a.include?(current_user.id)%>
          <%= f.submit 'Like' %>
        <% end %>
        <%if image.likes.to_a.count == 0%>
          Nobody likes this image! :(
        <%elsif image.likes.to_a.count == 1%>
          1 person likes this image!
        <%else%>
          <%= image.likes.to_a.count %> people like this image!
        <% end %>
      </div>
    <% end %>

    <%= form_for image, :url => image_dislike_path(image) do |f|%>
      <div class="text">
        <% if !image.unlikes.to_a.include?(current_user.id) && !image.likes.to_a.include?(current_user.id)%>
          <%= f.submit 'Dislike' %>
        <% end %>
        <%if image.unlikes.to_a.count == 0%>
          Nobody dislikes this image!
        <%elsif image.unlikes.to_a.count == 1%>
          1 person dislikes this image!
        <%else%>
          <%= image.unlikes.to_a.count %> people dislike this image!
        <%  end %>
      </div>
    <%  end %>
     
<br/>

    Comments ( <%= image.microposts.count %> )
   
    <%= form_for [image,@micropost] do |comment| %>
      <div class="field">
        <%= comment.text_area :content, placeholder: "Compose new comment..." %>
      </div>
      <%= comment.submit "Comment" %>
    <% end %>

<br/>
       
    <% @microposts.each do |m| %>
       
       <% if(m.image_id == image.id) %>
        <% if (m.user_id == current_user.id || current_user.admin?)%>
        
         <%= link_to "Delete", image_micropost_path(image, m),:method => :delete %>
    
            

        <% end %>

          <% @users.each do |user| %>
            <%if(user.id == m.user_id)%>
              <%= user.name.capitalize %>
            <% end %>
          <% end %>

        says: <b style="color: maroon;"> <%= m.content%></b>
  <br/>
         
       <% end %>
      <% end %>
<% end %>

<br/>
<hr/>

<% end %>
   

app/views/images/_image.html.erb
<!-- IMAGE START -->

<li class="  entry-item" data-url="http://9gag.com/gag/5425473" data-text="Everytime when using ctrl+c" gagid="5425473" itemtype="list" id="entry-5425473" style="">

<div class="content">
  <div class="img-wrap">
    <%= link_to(image_tag(image.picture.url(:medium)),image) %>
  </div>
  <div class="fatbigdick all-users-expand"></div>

</div><!--end div.content-->


</li>


<!-- IMAGE END -->

app/views/images/create.html.erb
<h1>Images#create</h1>
<p>Find me in app/views/images/create.html.erb</p>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <hr/>
  Simple Rails copy of 9gag by <%= link_to "Shifi", 'https://github.com/shifi/nine_gag', id:'link3' %>
  <hr/>
</footer>

app/views/layouts/_header.html.erb
<div id="headbar-wrap">


  <div id="searchbar_container">
    <div id="searchbar_wrapper">
      <div id="header_searchbar" style="display:none;">
        <div style="margin: 0px auto; position: static; overflow: hidden; height: 0px; "><div id="search_wrapper" style="margin: 0px; ">
            <form action="http://9gag.com/search">
              <input id="sitebar_search_header" type="text" class="search search_input" name="query" tabindex="1" placeholder="Search" autocomplete="off">
            </form>
        </div></div>
      </div>
    </div>
  </div>

  <div id="head-bar">

    <h1>
      <a class="logo" href="#">9GAG</a>
    </h1>
    <ul class="main-menu" style="overflow:visible">
      <li><a class="current" href="http://9gag.com/hot">Fun</a></li>
      <li><a href="http://9gag.com/fast" onclick="GAG.GA.track(&#39;Lab&#39;, &#39;Clicked&#39;, &#39;Go&#39;);">Fast</a></li>
      <li><a class="add-post " href="http://9gag.com/ch-submit" onclick="GAG.GA.track(&#39;New-Post&#39;, &#39;Clicked&#39;, &#39;Headbar&#39;);">Upload</a></li>
    </ul>
    <ul class="main-2-menu">




      <li id="headbar-signup-button" class="toggle-enabled" style="display: none; ">
      <a class="signup-button green" href="https://9gag.com/signup" label="Header" onclick=" rmt(&#39;http://goo.gl/4L7Xz?a=317&#39;); GAG.GA.track(&#39;Signup-Link&#39;, &#39;Clicked&#39;, &#39;Nav&#39;);">Y U No Signup?!</a>
      </li>




      <li><a href="https://9gag.com/login" class="button">Login</a></li>

      <li><a class="shuffle-button" href="http://9gag.com/random" onclick="GAG.GA.track(&#39;Random&#39;, &#39;Clicked&#39;, &#39;Nav&#39;);"><strong>Shuffle</strong></a></li>
      <li><a class="search-button search-toggler" href="javascript:void(0);"><strong>Search</strong></a></li>


    </ul>


  </div>
</div><!--end headbar-wrap-->

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>9gag <%=  yield(:title) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render "layouts/shim" %>
</head>
<body>
  <%= render "layouts/header"%>
    <div id="nav">
      <div class="left">
    <%= link_to "Home", root_path, id: "link2"%> |
    <%= link_to "Help", help_path, id: "link2"%> |
    <%= link_to "About", about_path, id: "link2" %> 
    <% if current_user %>
    | <%= link_to "Users", users_path, id: "link2" %>
      <% end %>
      </div>
    

      <div class="right">
    <% if current_user %>
        
      Hello <%= link_to current_user.name.capitalize, profile_path, id: "link2"%>!
      <%= link_to "Sign out", destroy_user_session_path, :method => :delete, id:"link2" %>
  
  <% else %>

  Please <%= link_to "sign_in", new_user_session_path, id: "link2" %> or
  <%= link_to "sign_up", new_user_registration_path, id: "link2" %>!

 <% end %>
      </div>
    



</div>
  <p style="color: green"><%= notice %></p>
  <p style="color: red"><%= alert %></p>
<br/>
<%= yield %>
  
<br/>
<%= render 'layouts/footer' %>
<br/>
<%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/micropost/_micropost.html.erb
<li>
  <span class="content"><%= micropost.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
  </span>
</li>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/index.html.erb
<% @users.each do |user| %>

<% if current_user.admin? %>
<p>
<%= link_to "Delete", user_path(user.id), :method => :delete %>



<% end %>


<%=  user.name.capitalize %></p>

<h1><%= gravatar_for(user) %></h1>

<% end %>

app/views/users/show.html.erb
<% if current_user %>
<hr/><br/>

<%if @user.admin?%>
Admin
<%else%>
User
<%end%>
<br/><br/><hr/>

Name: <%= @user.name.capitalize %>
<br/>
Email: <%= @user.email %>
<br/>


<h1><%=  gravatar_for(@user) %></h1>
<hr/><br/>

Comments (<%= @user.microposts.count %>)
<br/>
Uploaded images (<%= @user.images.count %>)
<br/><br/><hr/>
<% end %>